liTest run scala.scalanative.junit.ExceptionInAfterTest started
liTest scala.scalanative.junit.ExceptionInAfterTest.test started
leTest scala.scalanative.junit.ExceptionInAfterTest.test failed: java.lang.UnsupportedOperationException: Exception in after(), took <TIME>
e2scala.scalanative.junit.ExceptionInAfterTest.test::java.lang.UnsupportedOperationException: Exception in after()::true
ldTest scala.scalanative.junit.ExceptionInAfterTest.test finished, took <TIME>
liTest run scala.scalanative.junit.ExceptionInAfterTest finished: 1 failed, 0 ignored, 1 total, <TIME>
d
